### ISSUE TITLE
Suggestion on parallel example

### ISSUE THREAD

**Issue by alvinjeffery** [PheWAS/PheWASExamples#1]
I noticed in the example that you had ```cores=4```, and to help with running an example for those unfamiliar with R, would you consider something like ```cores=detectCores()-1``` to prevent using the all the machine's cores?

**Comment by RobertJCarroll** [comment]
I went ahead and just changed the default to one. It's expected that the user would read and follow along with the example, but in those cases the code is simply executed it does make sense to not have problematic behavior. detectCores() is not necessarily a prudent approach to recommend, given that it in some scenarios it could yield very large and unreasonable counts. Thanks!
